server:
  port: 9095

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:hz-register}:${NACOS_PORT:8848}
      config:
        server-addr: ${NACOS_HOST:hz-register}:${NACOS_PORT:8848}
  config:
    import:
      - optional:nacos:application-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-@profiles.active@.yml
